DELETE FROM users;
DELETE FROM products;
DELETE FROM transactions;
DELETE FROM reviews;

INSERT INTO users (first_name, last_name, email, hashed_password)
VALUES
    ('demo', 'user', 'demouser@demouser.com', 'pbkdf2:sha256:150000$Kae4NpQC$0f5d41ceda81c71f16e5c4f7c5651b12e3bb9aa631ff9c2c9a979a6781b7fe7f');

INSERT INTO products (name, price, description, imgurl, brand, category)
VALUES
    ('Canon EOS 6D Mark II', 139900, 'For superb performance on the go, the Canon EOS 6D Mark II camera puts full-frame performance into a compact, fully featured DSLR. Its 26.2 Megapixel CMOS sensor and DIGIC 7 Image Processor help deliver amazing results even at expanded ISO settings, making it great for challenging low-light situations as well as landscape, portrait and event photography. The EOS 6D Mark II also features an impressive optical viewfinder with 45 all cross-type AF points*, fast and accurate Dual Pixel CMOS AF and a Vari-angle Touch Screen LCD for Live View operation which helps create unique angles. With the EOS 6D Mark II''s speed to capture action and the versatility to create phenomenal photographs and Full HD 60p videos in numerous environments and lighting situations, the camera offers creative content makers a winning combination of advanced features in a portable package that''s as fun as it is powerful.', 'https://www.adorama.com/images/Large/ica6dm2.jpg', 'Canon', 1),
    ('Canon EOS 5D Mark IV', 249900, 'The EOS 5D Mark IV camera builds on the powerful legacy of the 5D series, offering amazing refinements in image quality, performance and versatility. Canon''s commitment to imaging excellence is the soul of the EOS 5D Mark IV. Wedding and portrait photographers, nature and landscape shooters, as well as creative videographers will appreciate the brilliance and power that the EOS 5D Mark IV delivers. Superb image quality is achieved with Canon''s all-new 30.4 Megapixel full-frame sensor, and highly-detailed 4K video is captured with ease.', 'https://www.adorama.com/images/Large/ica5dm4.jpg', 'Canon', 1),
    ('Canon EOS 1D Mark III', 649900, 'Featuring a Canon-developed 35mm full-frame CMOS sensor with approx.20.1 effective megapixels, the EOS-1D X Mark III camera is engineered with a new imaging system, designed to capture sharp and detailed images, even in low-light scenarios. This results in noise reduction in dark portions of the image even at high ISO speeds, and increased sensitivity that contributes to the EOS-1D X Mark IIIs high-speed image capture rate, accelerating frame-to-frame performance. The new sensor also includes Dual Pixel CMOS AF for high-speed, precise AF during Live View still and movie recording.', 'https://www.adorama.com/images/Large/ica1dxm3k_7.jpg', 'Canon', 1),
    
    ('Nikon Z7 FX-Format Mirrorless Camera w/ NIKKOR Z 24-70mm f/4 S Lens', 339695, 'Model: Nikon Z7Sensor Size: Full Frame Camera FormatResolution: 45 MPMax Video Quality: 4K 30fpsIn-Body Stabilization: 5-Axis OpticalSpecial Features: Bluetooth, Clean HDMI Out, TouchscreenConfiguration: Body & Lens A system that opens a new dimension of possibilities. A system inspired by the past but designed for tomorrow. A system only Nikon could create.' , 'https://www.adorama.com/images/Large/nkz7k.jpg', 'Nikon', 2),
    ('Nikon Z6 FX-Format Mirrorless Camera w/ NIKKOR Z 24-70mm f/4 S Lens', 239695, 'Characterized by its adaptability, the Nikon Z6 is the brand''s newest all around mirrorless camera system. Featuring a large diameter Z mount with a short flange distance of 16mm, the Z6 is part of Nikon''s next step in delivering higher image quality and more advanced optics. The camera features an FX-format 24.5MP BSI CMOS sensor and the EXPEED 6 Image Processing Engine to deliver exceptional processing speed and image quality with an impressive ISO sensitivity range of 100-51200. Effortlessly produce spectacular UHD 4K (3840x2160) 30p videos and 24MP images at up to 12 frames per second with the NIKKOR Z 24-70mm f/4 S zoom lens, which offers a versatile zoom range that''s ideal for a variety of shooting styles and subjects.','https://www.adorama.com/images/Large/nkz6k.jpg', 'Nikon', 2),
    ('Nikon Z50 DX-Format Mirrorless Camera w/ NIKKOR Z DX 16-50mm VR & 50-250mm VR Lenses', 119695, 'Creativity comes full circle. Z 50 is designed around Nikon''s revolutionary Z mount, the widest lens mount of any comparable camera system. A wider mount means more light, and more light means more of everything good—sharpness, contrast, focusing speed, low light performance and image quality.', 'https://www.adorama.com/images/Large/nkz50k2.jpg', 'Nikon', 2),
    ('Nikon D850 DSLR Camera Body', 299695, 'For shooting stills in continuous AF, the MB-D18 increases your total shot count to approx. 5,140 shots on a single EN-EL18C battery or up to 145 minutes of HD video. Check out this bundle: INKMBD18A. (The MB-D18 battery grip also works with EN-EL15 in regular mode). The D850 puts staggering image quality and impressive performance within reach of working photographers everywhere.', 'https://www.adorama.com/images/Large/inkd850.jpg', 'Nikon', 1),
    ('Nikon D750 DSLR Body', 149695, 'Full-frame freedom, outstanding agility and the convenience of built-in Wi-Fi®. For those who find inspiration everywhere, who switch between stills and video without missing a beat, who want the look only a full-frame DSLR can achieve and who love sharing their shots, the D750 is the tool to unleash your artistry. With features inspired by D4S and D810, the D750 brings dazzling image quality, cinematic video capabilities and pro-inspired handling in a nimble design with a tilting Vari-angle LCD and built-in Wi-Fi connectivity. Enthusiasts upgrading from a DX-format DSLR will marvel at the D750''s full-frame performance. Pros seeking a primary or secondary camera for fast-paced shoots will appreciate the D750''s familiar handling and speed. And filmmakers looking for a compact DSLR to bring a production to life or to capture B-Roll will find the D750 a perfect fit. The D750 is a thrilling centerpiece of an exceptional imaging system.', 'https://www.adorama.com/images/Large/inkd750_1.jpg', 'Nikon', 1),
    ('Nikon D3500 w/ AF-P DX NIKKOR 18-55mm f/3.5-5.6G VR Lens, Black', 49695, 'Nikon D3500 with AF-P DX NIKKOR 18-55mm f/3.5-5.6G VR Lens. Designed for entry-level users, the Nikon D3500 integrates impressive DSLR imaging capabilities into its compact and lightweight body. Armed with a powerful 24.2MP DX-format CMOS sensor and an EXPEED 4 image processor, the D3500 allows continuous shooting of up to 5fps and FHD 1080p video recording at 60fps. This sensor and image processor combination ensures high-quality imagery, with a native ISO sensitivity range of 100-25600 for better performance under a wide range of lighting conditions. To deliver ultra-sharp photos and videos, it features the same sensor design (which omits the optical low-pass filter) popularized by Nikon in 2012. It also features a 3-inch 921k-dot LCD screen that makes it easy to review captured images and shoot while on live view, plus the rear controls are arranged on the right-hand side of the camera for easy one-handed operation. This D3500 bundle includes the AF-P DX NIKKOR 18-55mm f/3.5-5.6G VR lens, which offers a 35mm-equivalent focal range of 27-82.5mm for near-wide-angle views and short zooms. With an integrated pulse stepping motor, an advanced optical design, and a Vibration Reduction (VR) image stabilization system, this lens makes it easier to achieve accurate focus and ultimately capture sharp and vibrant results.', 'https://www.adorama.com/images/Large/inkd3500k.jpg', 'Nikon', 1),
    
    ('Sony a99 II', 319800, 'Unprecedented resolution and unmatched speed. Capture 42.4MP at up to 12fps continuous shooting with AE/AF tracking and stunning 4K video. Stay focused with the world''s first 79 hybrid AF cross-point array for unmatched AF tracking and 4D Focus hybrid phase AF system that combines dedicated 79-point AF sensor and wide 399-point focal plane phase detection on the cameras imaging sensor.', 'https://www.adorama.com/images/Large/isoa99m2.jpg', 'Sony', 1),
    ('Sony Alpha a7R IV', 349800, 'Sony adds yet another high-performance full-frame mirrorless camera to its Alpha series with the new Sony a7R IV. This is the fourth edition of the a7R, which now comes with an updated 61MP Exmor R BSI CMOS sensor and BIONZ X image processor to render crisp and smooth images. It also includes the new UXGA (Ultra-XGA) OLED Tru-Finder, which has 5.76 million dots for enhancing details, brightness, and contrast. It also has a 15-stop dynamic range for rendering smooth and tonal gradations that improve the color quality of your images. The a7R IV has a native sensitivity range of ISO 100-32000, allowing you to work under various lighting conditions. Its updated Fast Hybrid AF system has a combination of 567 phase-detection points for quick and reliable autofocus tracking. The a7R IV is also capable of recording UHD 4K30 video while utilizing its various AF technologies, making it a big boon for filmmakers. Shoot comfortably and render exceptional image and video quality with the new Sony a7R IV.', 'https://www.adorama.com/images/Large/isoa7r4.jpg', 'Sony', 2),
    ('Sony Alpha a9 II', 449800, 'The brand-new Sony Alpha a9 II mirrorless camera boasts improved connectivity, a refined body design, and faster performance alongside the existing features of its predecessor. A full-frame 24.2-megapixel Exmor RS BSI-stacked CMOS sensor and an enhanced BIONZ X processor makes it a quick and responsive camera. The a9 II supports up to 20 fps of continuous shooting with its silent electronic shutter and has a mechanical shutter for capturing images at up to 10 fps. Shooting with this mirrorless body in different lighting conditions is possible thanks to its wide sensitivity range that can reach up to ISO 204800. The A9 II sensor features a 693-point autofocus system with intelligent subject tracking and Real-time Eye AF. It records Ultra HD 4K videos at up to 30 fps and includes Quick and Slow Motion modes. The camera also minimizes the appearance of camera shake by up to 5.5 stops thanks to its 5-axis SteadyShot INSIDE stabilization. The Sony Alpha a9 II is more ergonomic and has a better weather-sealed build and connectivity capabilities. It incorporates dual UHS-II SD card slots for versatile storage and allows quick file-sharing using its Ethernet port, 5.0 GHz wireless sharing, and Bluetooth features.', 'https://www.adorama.com/images/Large/isoa9m2.jpg', 'Sony', 2),
    
    ('Olympus PEN E-PL8 Mirrorless Camera w/ ED 14-42mm f/3.5-5.6 II R Lens', 27999, 'Oympus is rolling out a bevvy of new products in its interchangeable-lens Micro Four Thirds lineup. Headlining is the compact, snapshooter-oriented Olympus Pen E-PL8. Included in the new line is a trio of lenses—a 30mm f/3.5 Macro, a super-fast, low-light specialist “normal” focal length 25mm f/1.2 Pro lens, and a superzoom 12-100mm f/4.0 zoom—and the Olympus FL-900R, a high-intensity, weatherproof, wireless flash.', 'https://www.adorama.com/images/Large/iomepl8wk.jpg', 'Olympus', 2),
    ('Olympus OM-D E-M10 Mark III Mirrorless Camera w/ 14-42mm Lens', 79900, 'You love photography, but let''s keep it real. You travel to enjoy your vacation, not to be your family''s on-staff photographer. You want a sharp shot of your dog''s epic mid-air catch, but you don''t have time to memorize a user manual. The E-M10 Mark III is just for you. It''s small and lightweight so it''s effortless to take along. The simple to use touch screen interface and exclusive Shortcut Button remove all mystery from camera settings. And foolproof image stabilization virtually eliminates motion blur and shake from your stills and 4K video. The E-M10 Mark III. Your photographic journey starts here.', 'https://www.adorama.com/images/Large/iomem103ks_1.jpg', 'Olympus', 2),
    ('Olympus OM-D E-M1X Mirrorless Digital Camera Body', 239900, 'The Olympus OM-D E-M1X is a versatile, fast, and highly reliable Micro Four Thirds mirrorless camera that offers a wide range of imaging capabilities to suit the needs of beginner and professional shooters. It features a high-resolution 20.4MP Live MOS sensor and two TruePic VIII image processors, providing excellent imaging power for continuous shooting (up to 60 frames per second), cinema-grade DCI 4K video recording, an extended ISO sensitivity range of 25600, and up to 7.5 stops of camera shake with its 5-axis sensor-shift image stabilization system. To complement the sensor design, the camera also has 121 cross-type phase-detection points and 121 contrast-detection areas to ensure fast and accurate autofocus performance.', 'https://www.adorama.com/images/Large/iomem1x.jpg', 'Olympus', 2),
    
    ('Fujifilm X-T30', 89900, 'The FUJIFILM X-T30 combines a sleek mirrorless camera with next-generation image-making technology to meet the ever-increasing needs of content creators, regardless of their skill level. Boasting a new 26.1MP APS-C X-Trans CMOS 4 sensor and X-Processor 4 Quad-Core CPU, the X-T30 provides beginners, advanced amateurs, and professionals with fast auto-focus, strong face detection, and power to create high-resolution stills with notable sharpness and clarity. Combined with its increased sensitivity range up to ISO 51200 and the ability to record 10-bit, 4:2:2 DCI 4K video through the camera''s HDMI port, the X-T30 is truly the perfect camera for releasing your creativity.', 'https://www.adorama.com/images/Large/ifjxt30b.jpg', 'Fujifilm', 2),
    ('Fujifilm X100F w/ Fujinon 23mm f/2 Lens', 129900, 'The original Fujifilm X-100, when it was introduced in 2013, was an instant hit for street photographers and photojournalists, thanks to its 23mm lens (35mm equivalent), high-quality APS sensor, and its striking resemblance to a well-known, red-dotted German camera favored by street shooters but costing several thousands of dollars more. The camera has undergone several upgrades, and today, the Fujifilm FinePix X-100F is the fourth generation of this now-legendary camera. It promises faster and more accurate autofocus and response times than its predecessors among its new and improved features.', 'https://www.adorama.com/images/Large/ifjx100fs_4.jpg', 'Fujifilm', 2),
    ('Fujifilm X-T4 Mirrorless Camera', 169900, 'The Fujifilm X-T4 combines outstanding video capabilities and stills with improved workflow and functionality features. This compact mirrorless camera has an APS-C-format 26.1MP X-Trans CMOS 4 sensor and a wide native sensitivity range of ISO 160-12800 for better low-light performance. The X-T4 can record DCI or UHD 4K footage at 60 fps internally. It can also record Full HD footage at up to 240 fps for ultra slow-motion playback. The camera has a micro-HDMI port for 10-bit 4:2:2 recording and includes an F-Log gamma setting that gives a flat picture for color grading during post-processing. The X-T4 features Film Simulation modes that mimic classic Fujifilm types like Provia, Velvia, Astia, and more. The X-T4 camera body comes in either black or silver and can be bought separately or with two kit lens options. This camera can come with either an XF 16-80mm f/4 R WR OIS Lens or an XF 18-55mm f/2.8-4 R WR OIS Lens. Shoot stills and videos easily and come up with high-quality outputs with the new Fujifilm X-T4 mirrorless camera.', 'https://www.adorama.com/images/Large/ifjxt4b.jpg', 'Fujifilm', 2),
    ('Fujifilm X-T3 Mirrorless Camera w/ XF 18-55mm f/2.8-4 Lens', 189900, 'The Fujifilm X-T2 received praise for its excellent image quality, but this time around, the engineers at Fujifilm found a way to top that achievement. The X-T3 adopts the X-trans CMOS 4 and X-Processor 4, giving it the highest, fastest quality of the X series. The sensor and processor combined allow for fast lenses in bright shooting conditions, making it a serious improvement over the X-T2.', 'https://www.adorama.com/images/Large/ifjxt3sk.jpg', 'Fujifilm', 2),

    ('Leica M-A(Typ 127)', 519500, 'The Leica M-A TYP 127 is a 35mm film rangefinder camera characterized by its simplicity and unobtrusiveness. As a completely mechanical camera, no battery is required for operation and the only exposure control offered is a choice of shutter speed, up to 1/1000 sec. A large, bright 0.72x-magnification viewfinder pairs with a precise rangefinder mechanism to enable comparative manual focusing control with M-mount lenses, along with parallax-corrected compositional framing. The body features black-colored chromed brass top and bottom covers, as well as an all-metal body design, to offer both durability as well as an aesthetic, minimal appearance. Designed for intuitiveness and efficient operability, the precision afforded by the M-A serves to complement a straight-forward working method.', 'https://www.adorama.com/images/Large/lcmabk.jpg', 'Leica', 3),
    ('Leica MP', 529500, 'The LEICA MP is a tool. Made by hand, created for the photographer''s craft. Tailored to the decisive photographic parameters. In compact form, with clean design, clearly laid out. Unobtrusive, quiet, reliable. Concentrated technology for concentrated photography, without distraction by automation. For pictures that only a photographer can see, compose and record. Modern, because it captures the present. Current, because all its features have been optimized. Traditional, because it builds on the accumulated experiences of the pioneer in 35 mm camera construction. Not a photographic whim, but a camera for life.', 'https://www.adorama.com/images/Large/lcmp72b.jpg', 'Leica', 3),
    ('Leica M10-P', 879500, 'The M10-P is Leica''s newest addition to their line of sleek and sophisticated digital M-series rangefinders. Designed to be one of their best yet, the classy and minimalist M10-P features the quietest shutter ever to be integrated into any film or digital M-series camera. It is also equipped with an enhanced 24MP Full-Frame CMOS sensor and Leica''s Maestro II Image Processor to deliver high-resolution 24MP photos at up to 5 frames per second, as well as an extended dynamic range and high ISO sensitivity of up to 50,000. Loyalists will love the familiar slim body that is reminiscent of its twin model, the M10. An enlarged optical viewfinder with 0.73x magnification and a 3-inch rear touchscreen LCD monitor (which features scratch-proof Gorilla Glass) provides accurate focusing and creative compositional freedom, while a dedicated control dial allows for quick ISO adjustments during demanding shooting scenarios. A built-in Wii-Fi module enables wireless sharing and connection to a mobile device for remote control of camera functions. The Leica M10-P has two color variants: chrome black and silver. It also noticeably lacks the iconic red Leica badge in front, making it an attractive choice for those who want a professional-quality camera without standing out from the crowd.', 'https://www.adorama.com/images/Large/lcm10ps.jpg', 'Leica', 3),

    ('Canon EF 24-70mm f/2.8L II USM', 159900, 'The popular Canon EF 24-70mm f/2.8L II USM standard Canon zoom lens for DSLRs has been redesigned to exceed the demanding expectations of professional photographers. Its optical performance has been improved, thanks to a new Super UD lens element and a pair of UD elements designed to minimize chromatic aberrations along the edges and corners when shooting at wide angle. Featuring optimized lens coatings, color blur and ghosting have been reduced, and the resulting images offer outstanding color and contrast to meet the needs of nearly any assignment. It is the new and improved version of Canon''s workhorse standard pro zoom lens.', 'https://www.adorama.com/images/Large/ca2470.jpg', 'Canon', 4),
    ('Canon EF 50mm f/1.4 USM', 34900, 'Standard lens featuring superb quality and portability. Two high-refraction lens elements and Gaussian optics eliminate astigmatism and suppress astigmatic difference. Crisp images with little flare are obtained even at the maximum aperture.', 'https://www.adorama.com/images/Large/ca5014afu.jpg', 'Canon', 4),
    ('Canon EF 85mm f/1.2L II USM', 199900, 'The Canon EF 85mm f/1.2L II USM is a medium telephoto prime lens that is considered the ultimate professional portrait photography lens because of its extremely wide aperture, which results in a narrow depth of field and dramatic focus fall-off. Its superb floating optical system and aspherical lens element produce outstanding quality images with minimal reflections, glare and ghosting. As a Canon L-series lens, it is weather-sealed against moisture and dust, and image quality rivals prime lenses.', 'https://www.adorama.com/images/Large/ca85122afu.jpg', 'Canon', 4),
    ('Canon RF 35mm f/1.8 Macro IS STM Lens', 49900, 'Known for providing the most natural perspective, the 35mm is yet another photography staple that many shooters simply can''t leave home without. The RF 35MM F/1.8 IS MACRO STM from Canon''s new EOS R full-frame mirrorless system is a versatile tool that can be utilized for travel shooting, close-up work, landscape photography, and more. Compact, lightweight, and travel-friendly, this wide-angle macro prime offers 0.5x magnification with a minimum focusing distance of 6.7 inches, plus it has a maximum aperture of f/1.8 for incredible low-light capabilities and a rounded 9-blade diaphragm for beautiful bokeh. The integrated Dual Sensing IS (5-stop image stabilization) helps combat camera shake while the STM motor ensures silent focusing—both of which make this a great videography lens. Like other RF lenses, the 35mm f/1.8 IS MACRO STM has a dedicated control ring that enables quick, tactile exposure adjustments while looking through the EVF. It also takes advantage of the RF mount, which has a 12-pin connector for fast lens-to-camera communication and a short back focus design for enhanced optical performance. Meanwhile, the lens itself features an advanced optical design and Super Spectra Coating, ensuring exceptionally sharp results with amazing clarity throughout the entire frame.', 'https://www.adorama.com/images/Large/car3518.jpg', 'Canon', 5),
    ('Canon RF 24-105mm f/4 L IS USM Lens', 109900, 'The RF 24-105mm f/4L IS USM is a premium walkaround lens from Canon''s new line of RF lenses within their EOS R full-frame mirrorless system. Characterized by its exceptional focal range and fixed maximum aperture of f/4, this highly versatile piece of glass is great for capturing more of a scene at the widest focal length, zooming in on faraway objects from a distance at the longest focal length, and covering a variety of shooting scenarios in between. Its nine rounded aperture blades are also designed to produce pleasing circular and velvety smooth bokeh. Shooting sharper images, even in low-light conditions, is made easier with up to five stops of image stabilization. The new and configurable Control Ring can be used to intuitively adjust different exposure settings, including the aperture, ISO, and exposure compensation. The lens also utilizes a ring-type NANO USM autofocus motor for achieving fast and accurate yet smooth and noiseless focusing in both photo and video modes. The RF 24/105mm f/4L IS USM features the L-series dust, moisture, and weather-resistant lens body, and is specifically designed for use with Canon''''s full-frame EOS R mirrorless camera.', 'https://www.adorama.com/images/Large/car241054.jpg', 'Canon', 5),
    ('Canon EF-M 22mm f/2 STM Lens', 24900, 'The Canon EF-M 22mm f/2 STM Lens is a moderate wide-angle lens that''s exclusively designed for the EOS M Digital Camera. It features smooth and continuous AF with a built-in stepping motor, as well as a seven blade circular aperture. The lens is lightweight and small enough to carry around with you everywhere. Plus, it has a minimum focusing distance of 5.9 (15 cm) and a bright f/2 aperture, which affords exceptional low-light performance.', 'https://www.adorama.com/images/Large/ca22f2.jpg', 'Canon', 5),
    
    ('Nikon 50mm f/1.8G AF-S NIKKOR', 21695, 'This updated classic with a fast maximum aperture is ideal for everyday shooting, perfect in low lighting situations and great for producing images with beautiful background blur (Bokeh). The AF-S NIKKOR 50mm f/1.8G includes Silent Wave Motor technology (SWM) for fast and precise autofocus, M/A Focus Mode Switch for seamless changes between manual and autofocus operation and an aspherical lens element for outstanding optical performance with high contrast.', 'https://www.adorama.com/images/Large/nk5018gu.jpg', 'Nikon', 4),
    ('Nikon 35mm f/1.8G AF-S NIKKOR', 19695, 'AF-S DX NIKKOR 35mm f/1.8G lens, is the first fixed focal length, fast-aperture DX-format lens that affords photographers superb image quality along with the creative possibilities and versatility of the classic 50mm focal length (FX-format equivalent of 52mm). When mounted on a DX-format camera body, it enables photographers to document their world with a lens that produces a picture angle similar to the field of vision as seen through the human eye. Whether new to D-SLRs or a seasoned enthusiast, users will appreciate the extreme low-light performance and the expanded ability to dramatically separate the subject and background with the new 35mm DX lens'' wide f/1.8 aperture.', 'https://www.adorama.com/images/Large/nk5018gu.jpg', 'Nikon', 4),
    ('Nikon 24-70mm f/2.8G ED-IF AF-S NIKKOR', 159695, 'The Nikon 24-70mm f/2.8G ED-IF AF-S Nikkor lens is a fast mid-range wide-angle-to-medium-telephoto zoom lens optimized for full-frame Nikon DSLRs cameras. With a continuous wide aperture of f/2.8, quiet autofocus, and updated lens coating technologies, this lens is considered a workhorse for professional photographers and videographers thanks to its fine resolution and natural, accurate color representation. It will work with both film and digital Nikon cameras, and is compatible with both FX (full-frame) and DX (APS sensor) DSLRs. This lens is part of Nikon''s f/2.8 constant-aperture lineup of zoom lenses, which includes the AF-S Nikkor 14-24mm f/2.8G ED and AF-S Nikkor 70-200mm f/2.8G ED models, for pro-level coverage from 14-200mm focal lengths.', 'https://www.adorama.com/images/Large/nk2470afsu.jpg', 'Nikon', 4),
    ('Nikon NIKKOR Z 14-30mm f/4 S Ultra-Wide Zoom Lens', 129695, 'Characterized by its impressive wide-angle range, the Nikon NIKKOR Z 14-30mm f/4 S is an ultra-wide angle zoom lens that is designed for Nikon FX-format Z-series mirrorless cameras. Its an ideal tool for capturing breathtaking landscapes, architecture, astrophotography, and other photographic scenes and subjects that require broad fields of view. The constant maximum aperture of f/4 helps maintain a consistent exposure at every focal length. Four extra-low dispersion (ED) and four aspherical lens elements help reduce aberrations and distortions to produce sharper, clearer, and more accurate image details. Nano Crystal and Super Integrated Coatings on the lens also suppress flare and ghosting, resulting in higher contrast images with greater color fidelity. Complementing the optics are its fast, precise, and quiet autofocus stepping motor, along with full-time manual focus override that can be enabled during photo and video capture. And like any other NIKKOR Z-series lens, the 14-30mm f/4 S has a built-in programmable control ring that offers intuitive control over a variety of camera and exposure settings. The lens can also be stored in a more compact form, thanks to its retractable barrel design.', 'https://www.adorama.com/images/Large/nkz1430.jpg', 'Nikon', 5),
    ('Nikon NIKKOR Z 24-70mm f/2.8 S Lens', 229695, 'Meet the most versatile lens in the Z series stable. A powerful mid-range zoom that''s indispensable for a wide range of photo and video applications. From landscapes and street photography to full-length and environmental portaits, all with stunning clarity, high resolution and natural bokeh. Elevated by a new Multi-Fucous System, next generation les flare correction and advanced S-Line features and functionality, the NIKKOR Z 24-70mm f/2.8 S is a must-have lens that marks the sweet spot of performance, percision and optical superiority.', 'https://www.adorama.com/images/Large/nkz247028.jpg', 'Nikon', 5),
    ('Nikon NIKKOR Z 70-200mm f/2.8 VR S Lens', 259695, 'The NIKKOR Z 70-200mm f/2.8 VR S lens is a telephoto zoom that works with Nikon''s Z-mount full-frame mirrorless cameras. It offers a 70-200mm focal length coverage and a constant f/2.8 aperture. Nikon''s built-in optical VR image stabilization comes with this lens, and it provides five-stop compensation for camera shake. You can get exceptionally steady shots by using the in-body stabilization on Z Series models together with the VR stabilization. For quick and accurate AF, the NIKKOR Z 70-200mm f/2.8 VR S features multi-focusing. This system helps the lens deliver remarkably high optical performance when you shoot at shorter distances. Both attributes guarantee super-sharp and detailed images with fewer aberrations. Meanwhile, Nano Crystal and ARNEO coatings on the lens achieve less ghosting and flare for very crisp images. The NIKKOR Z 70-200mm f/2.8 VR S uses single fluorite and SR elements that make optical performance and agility better. It comes with a stepping motor (STM) for silent AF operation and less focus breathing while shooting videos, too. Lastly, a 9-blade aperture, a rugged and weather-sealed design, a dedicated Info Panel, and more features are available on this new mirrorless lens.', 'https://www.adorama.com/images/Large/nkz70200.jpg', 'Nikon', 5),
    
    ('Sony FE 12-24mm f/2.8 E-Mount Lens', 299800, 'Introducing the world''s widest full-frame constant F2.8 lens at 12-24mm3. Spectacular G Master resolution and drastically reduced chromatic aberration is realized from 3x Extreme Aspheric, 1x Aspheric, 2x Super ED (Extra-low dispersion) and 3x ED elements. Nano AR coating II suppresses reflections, flare and ghosting while the constant F2.8 and 9-blade circular aperture delivers on beautiful bokeh. Fast, precise autofocus tracking comes from 4x XD (Extreme Dynamic) linear motors.', 'https://www.adorama.com/images/Large/iso1224gm.jpg', 'Sony', 5),
    ('Sony FE 85mm f/1.8 E-Mount Lens', 59800, 'There''s nothing like the sharpness and smooth bokeh of a well-designed mid-range telephoto prime lens for portraiture, and the Sony FE 85mm E Mount Lens is a standout choice. It features a compact, lightweight design for mobility, with high-performance optics and a large F1.8 maximum aperture that deliver outstanding image quality. An excellent second lens for both full-frame and APS-C camera users.', 'https://www.adorama.com/images/Large/iso8518.jpg', 'Sony', 5),
    ('Sony FE 24-105mm f/4 G OSS E-Mount Lens', 139800, 'From 24 mm to 105 mm and F4 aperture throughout the zoom, the high-performance G Lens offers consistently high image quality. In addition to outstanding optical performance, it has a compact, lightweight design for portability and mobility befitting the E-mount system. Fast, precise AF and high reliability add to the broad utility of this fine zoom lens.', 'https://www.adorama.com/images/Large/iso24105e.jpg', 'Sony', 5),
    ('Sony 70-400mm F4-5.6 G Series SSM Super Telephoto Lens', 219800, '70-400 mm F4-5.6 G telephoto lens for A-mount cameras. Nano AR coated and quick, quiet AF that locks on to moving subjects', 'https://www.adorama.com/images/Large/iso70400.jpg', 'Sony', 4),
    ('Sony 50mm f/1.4 Lens for A-Mount', 44800, 'Let in more light with an extremely bright 50 mm F1.4 lens. Extremely bright with superlative corner-to-corner resolution, superior clarity, and low flare. Ideal for general purpose shooting, portraits and interiors in natural light. Circular aperture for beautiful defocused effect.', 'https://www.adorama.com/images/Large/iso5014d.jpg', 'Sony', 4),
    ('Sony 16-80mm f/3.5-4.5 Vario-Sonnar T* A-Mount Lens', 99800, 'The SAL1680Z is a superb single-lens solution for many APS-C format photographers. Its 35 mm equivalent 24–120 mm range may be all you''ll ever need for day-to-day shooting. And of course it delivers acclaimed ZEISS® optical performance and handling, with image quality that rivals the best prime lenses at any focal length. An ideal introduction to ZEISS® quality for A-mount APS-C format bodies.', 'https://www.adorama.com/images/Large/iso168035z.jpg', 'Sony', 4),
    
    ('Olympus M. Zuiko 7-14mm f2.8 & 40-150mm F2.8 & ED 300mm F/4.0 Lenses', 579700, 'Heavyweight performance, lightweight portability. Though it is amazingly light and compact, the M.Zuiko Digital ED 7-14mm PRO lens is a heavy hitter in the field. This lens is portable and weatherproof so you can take it anywhere. And with an ultra-wide angle of view and a bright f2.8 maximum aperture, you''ll capture more of every scene, from sprawling daytime panoramas to electric, super-sharp night scenes.', 'https://www.adorama.com/images/Large/iom7140300lk.jpg', 'Olympus', 5),
    ('Olympus M. Zuiko Digital ED 12-40mm f/2.8 Lens', 99900, 'Want to pair your Olympus with a sophisticated, high-quality lens that''s as versatile as it is sharp? Then meet the OLYMPUS ED 12-40 F/2.8 PRO M4/3 LNS BLK, a lens capable of handling everything from night photography to sports and action to weddings—sometimes, all at once. Depending on the wedding.', 'https://www.adorama.com/images/Large/iom1240b.jpg','Olympus', 5),
    ('Olympus M. Zuiko Digital ED 40-150mm f/4-5.6 R Zoom Lens', 9900, 'What kinds of features make a high-performance zoom lens, well, high-performance in the first place? You''ll have to forgive us - it''s a bit of a trick question. After all, those same features are the exact kinds of features that make the OLYMPUS M. Zuiko Digital ED 40-150mm f/4-5.6 R MICRO 4/3 such a compelling candidate for your next zoom lens purchase.', 'https://www.adorama.com/images/Large/iom40150rms.jpg', 'Olympus', 5),

    ('Fujifilm XF 16mm F/2.8 R WR Lens', 39900, 'The FUJINON XF 16mm F2.8 R WR features a focal length equivalent to 24mm (in the 35mm format) and has a maximum aperture of F2.8. It helps to deliver the best results from Fujifilm''s unique X-Trans CMOS sensors. Small and lightweight, the lens offers very high resolution performance due to the optical design. The XF 16mm F2.8 R WR lens adopts an inner focusing system driven by a stepping motor for faster and quieter auto-focusing. Metal parts are used extensively on the exterior providing a premium yet robust feel, while the aperture and focusing rings have been designed to be comfortable and easy to use. The lens is also weather and dust resistant and operates in temperatures as low as -10 deg. C, making it ideal for shooting in a variety of conditions.', 'https://www.adorama.com/images/Large/ifj232b.jpg', 'Fujifilm', 5),
    ('Fujifilm XF 23mm F/2 R WR Lens', 44900, 'The XF23mm F2 R WR is a wide-angle lens with advanced image resolution, capable of drawing out the full performance of Fujifilm''s proprietary X-Trans CMOS sensor. It has a similar size and design flair of the existing XF35mm F2 R WR, to make up a stylish collection of compact lenses. The inner-focus AF system uses a stepping motor to drive the focusing group of lens elements for silent and fast autofocus. The metal exterior gives a sense of premium quality and robustness, and the aperture ring and focus ring have been designed for optimum operability. The lens is also weather and dust resistant and operates at temperatures as low as -10°C, making it an ideal choice for outdoor photography.', 'https://www.adorama.com/images/Large/ifj232b.jpg', 'Fujifilm', 5),
    ('Fujifilm XF 35mm F/2 R WR Lens', 39900, 'The FUJINON XF35mmF2 R WR offers a focal length equivalent to 53mm with the angle of view similar to that of the human eye and a maximum aperture of F2.0. It delivers sharp images with rich bokeh. The optical construction of 9 elements in 6 groups (including two aspherical elements) achieves the perfect balance of high image quality and compact size. The lens features the smallest diameter of the line-up and thanks to the inner focus system and stepping motor, it achieves an autofocus time of just 0.08 sec. The exterior of the lens is weather and dust-resistant and can work in temperatures as low as -10deg.C. The lens is ideal for any scene and application. This is the new standard for all photography fans.', 'https://www.adorama.com/images/Large/ifj352xf.jpg', 'Fujifilm', 5),
    
    ('Leica Summilux-M 35mm f/1.4 ASPH FLE Lens', 589500, 'The Leica SUMMILUX-M 35 mm f/1.4 ASPH. is a further revised version of the popular wide-angle lens of the Leica M rangefinder system. Thanks to the latest developments in the fields of optics and precision engineering, the new 35 lens sets a whole new standard in the fast wide-angle lens portfolio. Regardless of whether it''s a matter of selective focus in the close-up range, high-contrast available light applications or landscape shots with immense depth of field, the lens delivers persuasive arguments in any situation. In addition to the new FLE (floating elements) design, this lens features a full-metal, rectangular, screw-mount lens hood that contributes significantly to the even more compact dimensions of the lens.', 'https://www.adorama.com/images/Large/lc3514mafu.jpg', 'Leica', 6),
    ('Leica Summicron-M 35mm f/2.0 ASPH Lens', 369500, 'This outstanding new classic prime lens offers exceptional image performance and unique bokeh. Despite its high speed and impressive imaging quality, its dimensions are astoundingly compact. Together with this lens, every Leica M becomes an extremely compact and elegant photographic tool. The Summicron-M features a rectangular, full-metal lens hood with a screw mount. A screw-in protector ring is provided to protect the filter thread of the lens when the hood is not in use.', 'https://www.adorama.com/images/Large/lc352mub.jpg', 'Leica', 6),
    ('Leica Summilux-M 50mm f/1.4 ASPH Lens', 439500, 'The optical structure of the LEICA SUMMILUX-M 50mm f/1.4 ASPH. consists of eight lens in 5 groups. Glass with anomalous partial dispersion (elements 2/3) was used to ensure correct color rendition. Lens element 2 is made of a fluorite-type glass while lens element 3 is made from glass originating from the former Leitz glass laboratory. Lens element 4 has an aspherical surface. Lens elements 1, 6 and 7 are made of glass with a very high refractive index to minimize monochromatic aberrations.', 'https://www.adorama.com/images/Large/lc5014mn.jpg', 'Leica', 6),

    ('Canon Speedlite 600EX II-RT', 49900, 'The Speedlite 600EX II-RT delivers impressive power, responsive performance and advanced, wireless communication for those who demand the very best in flash photography. Featuring improved continuous performance up to 2.0x* faster than its predecessor, the Speedlite 600EX II-RT performs at a phenomenal speed, and reliably at that - new Quick Flash settings and a flash-readiness indicator help ensure priority shutter operation, even when the flash isn''t fully recharged. It''s also built for fast, convenient use virtually anywhere for any situation, with improved combination button and dial controls, a refined dust- and water-resistant body and new accessories tailor-made for enhanced lighting effects. For speedy and comprehensive flash photography on the go, the Speedlite 600EX II-RT delivers portable, professional performance with ease.', 'https://www.adorama.com/images/Large/ca600ex2.jpg', 'Canon', 7),
    ('Canon Speedlite 430EX III-RT', 24900, 'For stunning flash photography even in complex lighting environments, Canon''s new Speedlite 430EX III-RT offers a fantastic combination of advanced features and simple operation. Compact in size, yet powerful in range, the Speedlite 430EX III-RT not only provides a portable light source, it has easy to manage features that can enhance contrast, color temperature, brightness and focus of light for more natural-looking photography. Whether bouncing the light source off a wall or ceiling, using its integrated Catchlight panel to brighten up a subject''s face, or using its bounce adapter to soften the intensity of the flash beam, the Speedlite 430EX III-RT is impressively versatile. With convenient custom and personal functions, speedy recycle times and advanced wireless photography options, the Speedlite 430EX III-RT can be an indispensable accessory for photographers ready to take their flash photography to the next level.', 'https://www.adorama.com/images/Large/ca430ex3u.jpg', 'Canon', 7),
    ('Canon Flashpoint Zoom Li-on TTL', 17900, 'The Flashpoint Zoom Li-on R2 TTL Flash for Canon represents a significant breakthrough in speedlight power technology with the introduction of full R2 Remote TTL connectivity and interaction with all Canon strobe functions. From standard ETTL, to Exposure Compensation (FEC), FV Lock, High Speed Sync, and an automatically zooming flashhead, all the way to complete ETTL II control connectivity with other Canon flashes, group control, Slave and Master options, and advanced flash functions, the Zoom Li-on flash takes you as far as you want to go.', 'https://www.adorama.com/images/Large/fplfsmzl2ca.jpg', 'Canon', 7),
    
    ('Nikon SB-700 TTL AF Shoe Mount Speedlight Flash', 32695, 'The i-TTL-optimized SB-700 offers the perfect balance of exposure, performance and portability for any photographer on the go. Its flexible flash head provides creative lighting freedom for nearly any subject. Achieve brilliant results and seamless lighting system integration with hot shoe operation or wirelessly as a master, commander or remote light source.', 'https://www.adorama.com/images/Large/nksb700afu.jpg', 'Nikon', 7),
    ('Nikon SB-5000 AF Speedlight Flash', 59695, 'Nikon SB-5000, a first for Nikon, the flash operates via radio frequency and will operate without a direct line of sight for a range of up to approx. 98 feet (30 meters). This new-found flexibility lets photographers place lights in different rooms, around corners and work seamlessly in bright ambient light with maximum efficiency. When paired with the WR-R10 and the D5 or the D500, this Speedlight can control up to six groups (A-F) or 18 Speedlights for truly advanced wireless lighting. It is also possible to perform Advanced Wireless Lighting using either radio-controlled (up to three groups) and/or optical-controlled units (up to three groups) by simply attaching a conventional, optical-control Nikon Speedlight or the SU-800 Commander (as a master or commander unit) and a WR-R10 (as a commander) onto the D5.', 'https://www.adorama.com/images/Large/nksb5000u.jpg', 'Nikon', 7),
    
    ('Sony HVL-F45RM Compact External Radio Wireless Flash', 36800, 'Supply powerful lighting with the compact high-performance HVL-F45RM clip-on flash. Explore freedom of built-in wireless radio control in multi-flash settings and conventional optical wireless communication. Easy operation, excellent reliability, expert results — especially for enthusiasts of compact α E-mount interchangeable-lens cameras. Dust and moisture-resistant design.', 'https://www.adorama.com/images/Large/isohvlf45rm.jpg', 'Sony', 7),
    ('Sony HVL-F60RM Wireless Radio Control Shoe Mount Flash', 54800, 'The HVL-F60RM clip-on flash unit features high GN60 power, high-speed continuous shooting support and fast operation: ideal for advanced to professional users. Wireless radio commander/receiver functionality is included.', 'https://www.adorama.com/images/Large/isohvlf60rm.jpg', 'Sony', 7),
    
    ('Olympus FL-LM3 Replacement Flash', 6999, 'The Olympus FL-LM3 Replacement Flash is suitable for the OM-D E-M5 Mark II camera body. Dustproof/splashproof. Has a guide number of 30 (9.1m) ISO100 and is capable of bounce photography. Only compatible with the OM-D E-M5 Mark II.', 'https://www.adorama.com/images/Large/iomfllm3.jpg', 'Olympus', 7),
    ('Olympus FL-700WR Wireless Flash', 29900, 'The high-intensity FL-700WR boasts a guide number of 42 meters (at ISO 100) and covers a wide range of focal lengths with an electronic zoom head. A built-in wide panel enables you to use wider focal length lenses and have perfect coverage, and a catchlight panel illuminates your portrait subjects'' eyes effortlessly.', 'https://www.adorama.com/images/Large/iomfl700wr_2.jpg', 'Olympus', 7),
    
    ('Fujifilm EF-X20 TTL Flash', 19900, 'The Fujifilm EF-X20 Flash was designed for the X Series Camera. A switch lets you choose between two modes: Auto, which automatically optimizes the flash for daylight indoor and outdoor shots in low light, and Manual for manual control.', 'https://www.adorama.com/images/Large/ifjefx20.jpg', 'Fujifilm', 7),
    ('Fujifilm EF-X500 TTL Flash', 44900, '• Maximum guide number approx. 50 (ISO100•m) / 164 (ISO100•ft). • Zooming the illumination angle for the focal lengths of 24mm - 105mm and covering the illumination angle of around 20mmwhen the wide panel is used. • Flash head that can be tilted up by 90 degrees, down by 10 degrees, to the left by 135 degrees and to the right by 180 degrees for bouncing light. • Equipped with LED video light that can also be used as AF assist light and catchlight. • Registers up to ten combinations of various settings. Register settings to suit a specific shooting condition in advance, so that they can be activated quickly when required', 'https://www.adorama.com/images/Large/ifjefx500.jpg', 'Fujifilm', 7),
    
    ('Leica SF 40 TTL Flash', 54500, 'Although the SF40 flash unit is particularly easy to use, it offers a full range of features like wireless TTL mode, high-speed sync and a nine-stage video lighting function. A guide number of 40 for focal lengths from 24 to 105 mm and a compact size make it an ideal companion when travelling light.', 'https://www.adorama.com/images/Large/ilcsf40.jpg', 'Leica', 7),
    ('Leica SF 60 TTL Flash', 65500, 'The new Leica SF 60 system flash is a compact powerhouse for Leica Cameras designed especially for the models of the S, SL, and M series. It is also fully compatible with the Leica Q and CL, for which it also offers TTL flash exposure control. The SF 60 is an extremely compact and powerful flash unit with an outstanding range of features, and is among the lightest and smallest of its performance class.', 'https://www.adorama.com/images/Large/ilcsf60.jpg', 'Leica', 7),

    ('Godox LC500R RGB LED Light Stick', 23900, 'Godox LC500R looks like a lightsaber, ideal for hand-holding. It is everything that you loved about its predecessor LC500, but with additional RGB mode and FX light effect to further free your creativity.', 'https://www.adorama.com/images/Large/golc500r.jpg', 'Godox', 8),
    ('Godox SL Series SL150W White LED Video Light', 20900, 'SL Series Video Light offers high light brightness and color rendering index with powerful LED beads. It creates stable light resource and even illumination for video recording, photojournalistic and wedding shooting, etc.', 'https://www.adorama.com/images/Large/gosl150w.jpg','Godox', 8),
    ('Flashpoint XPLOR 600 HSS Battery-Powered Monolight', 54900, 'Introducing the ultimate portable solution for studio quality flash with remote wireless totally independent of power cords and generators: The Flashpoint XPLOR600 MonoLight with R2 Radio Remote. It''s the most comprehensive self-contained full featured 600ws strobe that goes virtually anywhere, with wireless control, High Speed Sync, powered by its own massive internal and interchangeablehigh energy 11.1 volt Lithium Ion 8700mAh battery, capable of over 450 full power flash bursts on a single charge.', 'https://www.adorama.com/images/Large/fplfx600b.jpg', 'Flashpoint', 8),
    ('Flashpoint XPLOR 600PRO TTL Battery-Powered Monolight', 89900, 'The compact 600ws marvel invites you to go beyond the straights of wire dependency and soar into the free and easy heights only R2 Radio tenders.', 'https://www.adorama.com/images/Large/fplfx600ptb.jpg', 'Flashpoint', 8),
    ('Nova P300c Softbox', 14900, 'Get more dramatic light for your film or video with Aputure''s Nova P300c Softbox. This accessory works together with the brand''s new Nova P300c RGBWW LED Soft Light Panel. For even softer light, the Nova P300c softbox gives the fixture a 70x50cm (around 27.5x20”) size. It also controls the P300c''s beam angle using the included 40° Fabric Light Control Grid. Plus, Aputure has included a custom speedring bracket with Nova P300c softboxes. Sliding this bracket into the panel''s accessory slot seamlessly and firmly attaches the softbox to the light. You''ll get a ¼ grid diffusion sheet and a carrying bag with the Nova P300c softbox, too. The softbox''s carrying bag lets you store all accessories when you''re not using them. Aputure''s one-year limited warranty covers all Nova P300c softboxes.', 'https://www.adorama.com/images/Large/ap300csftbx.jpg', 'Aputure', 8),
    ('Glow Easy Lock Medium Deep White Fiberglass Umbrella', 3995, 'The Glow EZ Lock 33 BLACK/WHITE Deep Umbrella sports a dynamic parabolic shape with an unbeatable safe and sure EZ positive and lock system. No more open up and close down umbrella frustration or fumbling! The newly designed locking device surrounds the shaft, providing a comfortable place to slide the umbrella mechanism to open, and a generous wide button to release the shoot, painlessly.', 'https://www.adorama.com/images/Large/gluel33bw.jpg', 'Glow', 8),
    ('Glow 40 White Umbrella with Black Back', 1495, 'The Glow 40 White Umbrella gives an even, diffused lighting effect with soft shadow definition. With much attention to detail from fabric to frame ribs, this umbrella sets the standard for portable light control for people and subjects at fantastic value. This simple yet elegantly designed umbrella has a black opaque cover layer, limiting the light loss that naturally occurs through its optical white viscoelastic polymer fabric material.', 'https://www.adorama.com/images/Large/glu40wb.jpg', 'Glow', 8),
    ('Glow 40 Translucent Umbrella', 995, 'The Glow 40 Translucent Umbrella provides diffused lighting around a bright central burst. The lighting and effect can be varied by changing the distance from flashhead to umbrella. The moderately sized shoot though umbrella offers through diffusion quality when a lightbank is not practical. The lightweight spoke structure spreads the soft light over the area while keeping light lose very low. Whether used as a traditional wrap around reflected light source or as a more powerful direct diffuser, it will keep you cool in the shade.', 'https://www.adorama.com/images/Large/glu40t.jpg', 'Glow', 8),
    ('Photoflex Umbrella Convertible', 3995, 'Photoflex adjustable reflective Umbrellas were already the most versatile photographic umbrellas available today; and now they''re even better. The new andimproved umbrella line includes ribs and strut pivots that are now made from a fiberglass composite, which is not only stronger, but also offers better resiliency and durability than steel or aluminum.', 'https://www.adorama.com/images/Large/pfrut60.jpg', 'Photoflex', 8),

    ('Canon EDC-10 Sling Backpack', 3999, 'Designed to fit snugly against the body, this dark heather gray Canon EDC-10 Camera Sling Backpack can be rotated from your back to your front, so you can easily reach into its camera compartment. A large zippered opening gives you full access to the main compartment where you can keep one or two DSLR bodies and two or three lenses, plus accessories. The two-way zipper is water resistant and lockable for additional protection and security. The exterior is made from a lightweight and water-resistant nylon with a padded back for all-day comfort. It has a wide adjustable strap that can be worn across the body. A quick release buckle on the strap lets you get in and out of the bag quickly and easily, especially if it''s loaded with all your gear. For additional storage there is a dedicated tablet pocket, a large front mesh pocket with a bungee cord that can be cinched, and another large zippered front pocket for personal items like your wallet and keys.', 'https://www.adorama.com/images/Large/icaedc10.jpg','Canon', 9),
    ('Vivitar Gadget Bag', 2995, 'Designed for the traveler, inner dimensions 11"x6",6"', 'https://www.adorama.com/images/Large/vvgcb.jpg', 'Vivitar', 9),
    
    ('Leica Case with Carrying Strap for D-Lux 7 Camera', 16500, 'The high-quality case in brown leather guarantees optimum protection and perfect style when you are out and about with the Leica D-Lux. It comes complete with a matching carrying strap.', 'https://www.adorama.com/images/Large/lccsdl7br_1.jpg', 'Leica', 10),
    ('Leica Holster Case for Q2 Compact Camera, Leather', 24500, 'The Leica Holster Case is specially designed to carry and partially protect the Leica Q2 digital camera while allowing quick access to it. Made of premium black leather, the holster is constructed to cover the bottom, sides, and most of the front side of the camera. It also comes with a patented multi-angle connector and an adjustable rip-resistant belt that allows the user to achieve the perfect fit. With the holster laying flat against the front side of the body, it provides more stability compared to traditional camera straps while allowing quick camera draws for those split-second picture-perfect moments. The holster case is spacious enough to fit even the separately available handgrip as well as the mounted lens with hood.','https://www.adorama.com/images/Large/ilchq2.jpg','Leica', 10),
    
    ('Canon LP-E6 N Rechargeable Li-ion Battery Pack', 6495, 'The Canon LP-E6N Lithium-Ion Battery Pack is compatible with the LC-E6 and LC-E6E chargers. The battery is supplied with the camera and offered here as a spare or replacement part. Compatible with: EOS 5DS, 5DSR, 5D Mark IV, 5D Mark III, 5D Mark II, 6D, 7D, 80D, 70D, 60D', 'https://www.adorama.com/images/Large/icalpe6n.jpg', 'Canon', 11),
    ('Nikon EN-EL3e Rechargeable Li-ion Battery Pack', 4499, 'The camera''s fuel gauge accurately displays the remaining charge and number of shots since the last charging of the EN-EL3e. The battery can be charged using the MH-18, MH-18a or MH-19 battery chargers. Compatible with Nikon D50, D70, D70s, D80, D90, D100, D200, D300, D300S, and D700 SLR Digital Cameras.', 'https://www.adorama.com/images/Large/inkenel3e.jpg', 'Nikon', 11),
    ('Fujifilm NP-W126S Li-ion Battery', 6400, 'Fujifilm NP-W126S Li-Ion Battery is Specially designed for X-Series Digital Cameras.', 'https://www.adorama.com/images/Large/ifjnpw126s.jpg', 'Fujifilm', 11),
    ('Olympus BLN-1 Rechargeable Li-ion Battery', 4495, 'The Olympus BLN-1 Rechargeable Lithium-Ion Battery (1220 mAh) is for use with the Olympus OM-D E-M5 Mirrorless Digital Camera. It is compatible with the BCN-1 charger and requires approximately 3 hours to achieve a full charge from empty. It will support approximately 500 full charge cycles.', 'https://www.adorama.com/images/Large/iombn1_1.jpg', 'Olympus', 11),
    
    ('Manfrotto MT190 XPRO4 190 Aluminum 4-Section Tripod', 27988, 'The Manfrotto 190XPRO4 is a super-compact 4-section aluminum tripod with advanced features and excellent build quality. The key feature of the 190XPRO4 is its 90° center column mechanism, which allows the column to be extended vertically as normal, or horizontally to open up a wide range of framing and shooting possibilities; this makes the 190XPRO4 an extremely versatile tripod, suitable for a wide range of photography and video applications. The horizontal column mechanism is housed within the tripod''s top casting for compactness, but it is easily and quickly extended whenever you need it. Switching between vertical and horizontal column orientation requires no disassembly, and can even be done with a camera attached.', 'https://www.adorama.com/images/Large/bgmt190xp4.jpg', 'Manfrotto', 12),
    ('Manfrotto PIXI Evo mini Tripod', 4554, 'A wide range of shooting options for the mobile photographer. The PIXI EVO 2-Section Mini Tripod is compact enough to carry with you and offers diverse framing possibilities for your photographer work. Extremely lightweight and compact, the PIXI EVo 2-Section Mini Tripod is perfect for transportation. Combined with its sturdy aluminium structure, and you''ve got a reliable piece of equipment you can count on throughout your photography career.', 'https://www.adorama.com/images/Large/bgmtpxevbk.jpg', 'Manfrotto', 12),
    ('Joby GorillaPod', 5573, 'For devices that weigh less than 3kg (6.6lbs), the Joby GorillaPod 3K Kit easily adapts to support compact DSLR, mirrorless cameras or heavier flashes and is robust enough to hold multiple video lights or microphone with Jobys accessory kit or mounts. Weve paired the stand with our pro grade BallHead 3K, featuring separate pan joint for precise positioning. Its larger size makes this pair ideal as a grip for vlogging or live streaming.', 'https://www.adorama.com/images/Large/jogp3kkit.jpg', 'Joby', 12),
    ('Vanguard Alta Pro 263AB 100 Aluminum-Alloy Tripod', 14995, 'Pro 263AB tripod and SBH 100 ball head are an impressive pair. Alta Pro tripods have unmatched flexibility, stability and enabling more angle possibilities than ever before. Its innovative Multi-Angle Central Column (MACC) System allows users to move the central column from zero to 180-degree angles in variable vertical and horizontal positions making macro-photography and special wide-angle shots a breeze.', 'https://www.adorama.com/images/Large/vgt263ab100.jpg', 'Vanguard', 12),
    
    ('Sekonic L-308X-U Digital Light Meter', 21900, 'The world''s most versatile and affordable light meter for the next generation of photographers and cinematographers. Designed to meet the needs of the next generation of image makers; the new Flashmate L-308X-U, retains the compact and intuitive design of its predecessors the L-308S and L-308DC while blending their best features and functionality into one meter. Also added in are new features, such as the long-awaited LCD backlight, Aperture (F) priority (photo mode) and ISO 850 for cinema camera''s native ISO; making the L-308X-U truly the most versatile photo/cine meter on the market.', 'https://www.adorama.com/images/Large/sksk401305.jpg', 'Sekonic', 13),
    ('Sekonic L-858D-U Speedmaster Light Meter', 55500, 'With its 2.7" color touch screen and truly innovative and sophisticated features, the Sekonic Speedmaster L-858D-U leads the way to the next generation of light measurement control as the worlds first multi-function light meter for photographers and filmmakers. Leveraging over 60 years of experience in the image-making world with cutting-edge technology, the Sekonic Speedmaster L-858D-U has undergone a significant design change and boasts a comprehensive feature set sure to meet and exceed the demands of todays photographers and filmmakers. The first meter of its kind capable of measuring flash, while also being able to achieve an accurate ambient exposure reading in dimly lit scenes as low as 0.1 lx, the Sekonic L-858d-U provides image-makers of all levels with the critical exposure data they need to create stunning and beautiful imagery.', 'https://www.adorama.com/images/Large/skl858du.jpg', 'Sekonic', 13),
    ('Canon imageCLASS MF269dw All-in-One Wireless Laser Printer', 19900, 'The Canon imageCLASS MF269dw is a printer + scanner combo that is perfect for small to medium-sized businesses. Navigate the MF269dw''s many functions with its responsive LCD touchscreen. This printer also adds to your workplace efficiency by creating a direct Wi-Fi connection between your desktop, laptop, smartphone, or tablet. Smart scanning capabilities allow you to convert documents into searchable files at a rate of 11.6 black and white ipm and 7.7 colored ipm.', 'https://www.adorama.com/images/Large/icamf269dw_2.jpg', 'Canon', 13),
    ('Canon IVY Mini Photo Printer', 9900, 'Print your favorite photos from your smartphone and social media to share with friends. With the Canon IVY Mini Photo Printer app1 - customize your photos before you print them! Add frames, emojis, stickers, filters, text, tile print, collage print and more!', 'https://www.adorama.com/images/Large/icaimpr.jpg', 'Canon', 13),
    ('Epson SureColor P800 Inkjet Photo Printer', 119500, 'It''s here. Introducing the highly anticipated replacement for the Epson Stylus Pro 3880. Utilizing professional imaging technologies - including the unique Epson MicroPiezo AMC print head along with the latest Epson UltraChrome HD eight-color pigment ink set - the SureColor P800 is capable of producing the next-generation of photographic prints that will inspire us all.', 'https://www.adorama.com/images/Large/iescp800.jpg', 'Epson', 13);
